import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../../docs/form-drafts.js',import.meta.url),'utf8');
const saved=new Map(),ctx={state:{actor:{email:'one@example.com'}},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)},setTimeout,Date,Event:class{constructor(type){this.type=type;}}};
vm.createContext(ctx);vm.runInContext(source,ctx);const drafts=ctx.portalDrafts;
function form(){const input={name:'serialNumber',type:'text',value:'SN1'},file={files:[]},listeners={},notice={textContent:'',append(){},remove(){}};return {id:'receiveForm',dataset:{},isConnected:true,input,listeners,parentElement:{id:''},querySelectorAll:s=>s.startsWith('input[name]')?[input]:[],querySelector:s=>s==='.draft-notice'?notice:s==='input[type="file"]'?file:null,addEventListener:(name,fn)=>listeners[name]=fn};}
const initial=form();drafts.attach(initial);initial.input.value='Typed SN';initial.listeners.input();const key=drafts.key('createCase','new');assert.equal(saved.has(key),true);assert.equal(saved.get(key).includes('Typed SN'),true);assert.equal(saved.get(key).includes('token'),false);
const reloaded=form();drafts.attach(reloaded);assert.equal(reloaded.input.value,'Typed SN');
ctx.document={createElement:()=>({textContent:'',append(){}})};const changed=form();changed.input.value='Server changed';drafts.attach(changed);assert.equal(changed.input.value,'Server changed');assert.equal(changed.dataset.draftConflict,'true','Changed source must not auto restore stale values');delete ctx.document;
ctx.state.actor.email='two@example.com';const other=form();drafts.attach(other);assert.equal(other.input.value,'SN1','Another account must not receive the draft');
ctx.state.actor.email='one@example.com';assert.equal(saved.has(key),true,'Failed submission must retain draft');drafts.clearMutation('createCase',[null,{}]);assert.equal(saved.has(key),false,'Only successful mutation clears draft');
saved.set(key,JSON.stringify({base:{},data:{},savedAt:Date.now()-8*86400000}));drafts.attach(form());assert.equal(saved.has(key),false,'Expired drafts must be discarded');
const work={id:'',parentElement:{id:'panel-HS1'},querySelector:s=>s==='[name="workOrderId"]'?{value:'WO1'}:null};assert.deepEqual(Array.from(drafts.identify(work)),['updateWorkOrder','WO1']);
ctx.esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');ctx.today=()=> '2026-10-02';const html=fs.readFileSync(new URL('../../docs/entry.html',import.meta.url),'utf8');for(const name of ['issueRow','partRow','holdRow'])vm.runInContext(html.split('\n').find(line=>line.includes('function '+name+'(')),ctx);
function partsForm(){const f=form(),row={dataset:{partUsageId:'PART1',usedAt:'2026-10-02',note:'keep'},values:['','Name',1],querySelectorAll(){return this.values.map(value=>({value}));}},list={innerHTML:'',querySelectorAll:()=>[row]};f.id='';f.parentElement.id='panel-HS1';f.input={name:'workOrderId',type:'hidden',value:'WO1'};const old=f.querySelector;f.querySelector=s=>s==='[name="workOrderId"]'?f.input:s==='.row-list.parts'?list:old(s);return {f,row,list};}
const a=partsForm();drafts.attach(a.f);a.row.values=['','<replacement>',18];a.f.listeners.input();const b=partsForm();drafts.attach(b.f);assert.match(b.list.innerHTML,/&lt;replacement&gt;/);assert.match(b.list.innerHTML,/value="18"/);assert.match(b.list.innerHTML,/data-part-usage-id="PART1"/);
const quota=form();drafts.attach(quota);const originalSet=ctx.localStorage.setItem;ctx.localStorage.setItem=()=>{throw Error('Quota');};assert.doesNotThrow(()=>quota.listeners.input());ctx.localStorage.setItem=originalSet;
const entry=fs.readFileSync(new URL('../../docs/entry.html',import.meta.url),'utf8'),index=fs.readFileSync(new URL('../Index.html',import.meta.url),'utf8');assert.ok(entry.includes('form-drafts.js?v=1'));assert.ok(index.includes(source.trim()));assert.ok(entry.includes('portalDrafts?.clearMutation(name,args)'));assert.ok(index.includes('portalDrafts?.clearMutation(name,values)'));
console.log('Form drafts passed: account isolation, reload restore, preservation on failure, clearing after success, no token storage and both frontend integration.');
