/** Editor-only migration commands. Trailing underscore prevents google.script.run exposure. */
function xbsolarMigrationPreview_(){return xbmLocked_(function(){var actor=xbmManager_(),plan=xbmPlan_();xbmAssertNoActive_();var live=xbmReadLive_();xbmMatchBaseline_(plan,live);return {ok:true,planId:plan.id,planHash:plan.planHash,cases:plan.groups.length,newCases:plan.groups.filter(function(g){return g.createdCase;}).length,mergeCases:plan.groups.filter(function(g){return !g.createdCase;}).length,manualCases:plan.groups.filter(function(g){return g.protectedManualEdits;}).map(function(g){return {caseId:g.caseId,note:g.reviewNote};}),expectedCounts:plan.expectedCounts,chronologyWarnings:xbmCheckChronology_(plan),revision:getPortalDatabaseRevision_(),actor:actor.email,written:false};});}
function xbsolarMigrationPrepare_(){return xbmLocked_(function(){var actor=xbmManager_(),plan=xbmPlan_();xbmAssertNoActive_();xbmCommitConsent_(plan);var live=xbmReadLive_();xbmMatchBaseline_(plan,live);var old=xbmPointer_();if(old&&old.planHash===plan.planHash)throw Error('Gói đã có journal; dùng continue/status, không bắt đầu lại.');var folder=DriveApp.createFolder('XBSolar migration '+plan.id),backup=DriveApp.getFileById(plan.spreadsheetId).makeCopy('Backup trước '+plan.id,folder),manifest={id:plan.id,planHash:plan.planHash,bundleFileId:xbmProperties_().getProperty('XBSOLAR_MIGRATION_BUNDLE_FILE_ID'),folderId:folder.getId(),backupId:backup.getId(),state:'PREPARED',cursor:0,actor:actor.email,createdAt:new Date().toISOString(),revision:getPortalDatabaseRevision_(),protectedRanges:[]};var file=folder.createFile('manifest.json',JSON.stringify(manifest),'application/json');var pointer={manifestFileId:file.getId(),planHash:plan.planHash};xbmProperties_().setProperty('XBSOLAR_MIGRATION_JOURNAL',JSON.stringify(pointer));xbmProperties_().setProperty('XBSOLAR_MIGRATION_ACTIVE',plan.id);try{xbmProtect_(manifest);xbmSaveManifest_(manifest);return {ok:true,state:manifest.state,backupId:manifest.backupId,planId:plan.id};}catch(e){manifest.state='PREPARE_FAILED';xbmSaveManifest_(manifest);throw Error('Chuẩn bị chưa hoàn tất; giữ khóa nhập để tiếp tục hoặc rollback. '+e.message);}});}
function xbsolarMigrationContinue_(){return xbmLocked_(function(){var actor=xbmManager_(),plan=xbmPlan_(),m=xbmManifest_();xbmSameRun_(plan,m);xbmCommitConsent_(plan);if(m.state==='COMMITTED')return {ok:true,state:m.state,cursor:m.cursor};if(['PREPARED','RUNNING','FAILED','PREPARE_FAILED'].indexOf(m.state)<0)throw Error('Không thể tiếp tục ở trạng thái '+m.state);xbmProperties_().setProperty('XBSOLAR_MIGRATION_ACTIVE',plan.id);xbmProtect_(m);m.state='RUNNING';xbmSaveManifest_(m);var started=Date.now(),limit=xbmLimit_(),done=0;try{while(m.cursor<plan.groups.length&&done<limit&&Date.now()-started<180000){var g=plan.groups[m.cursor],file=xbmCaseJournal_(m,g),live=xbmReadLive_(),requests=xbmGroupRequests_(plan,g,live,false,m);if(requests.length)xbmBatch_(requests);var after=xbmReadLive_();xbmVerifyGroup_(plan,g,after);xbmAuditOnce_(actor,m,g,'commit',file.getId());xbmSync_(g.caseId);file.setContent(JSON.stringify({state:'COMMITTED',migrationId:m.id,group:g}));m.cursor++;m.revision=getPortalDatabaseRevision_();xbmSaveManifest_(m);done++;}if(m.cursor===plan.groups.length){xbmMatchExpected_(plan,xbmReadLive_());xbmUnprotect_(m);m.state='COMMITTED';xbmSaveManifest_(m);xbmProperties_().deleteProperty('XBSOLAR_MIGRATION_ACTIVE');}return {ok:true,state:m.state,cursor:m.cursor,total:plan.groups.length,processed:done,backupId:m.backupId};}catch(e){m.state='FAILED';m.lastError=String(e.message).slice(0,1200);xbmSaveManifest_(m);bumpPortalDatabaseRevision_();throw Error('Nhập tạm dừng ở '+m.cursor+'; journal/backup còn nguyên. Có thể continue hoặc rollback. '+e.message);}});}
function xbsolarMigrationStatus_(){return xbmLocked_(function(){xbmManager_();var m=xbmManifest_();return {state:m.state,planId:m.id,cursor:m.cursor,rollbackCursor:m.rollbackCursor,backupId:m.backupId,revision:m.revision,lastError:m.lastError||''};});}
function xbsolarMigrationRollback_(){return xbmLocked_(function(){var actor=xbmManager_(),plan=xbmPlan_(),m=xbmManifest_();xbmSameRun_(plan,m);var reason=clean_(xbmProperties_().getProperty('XBSOLAR_MIGRATION_ROLLBACK_REASON'));if(!reason||reason.length>500)throw Error('Cần lý do rollback (tối đa 500 ký tự).');if(m.state==='ROLLED_BACK')return {ok:true,state:m.state};if(m.state==='COMMITTED')xbmMatchExpected_(plan,xbmReadLive_());if(m.state!=='ROLLING_BACK'){if(m.state==='COMMITTED')m.rollbackCursor=plan.groups.length-1;else m.rollbackCursor=Math.min(m.cursor,plan.groups.length-1);m.rollbackReason=reason;m.rollbackActor=actor.email;m.rollbackDate=new Date().toISOString().slice(0,10);m.state='ROLLING_BACK';xbmProperties_().setProperty('XBSOLAR_MIGRATION_ACTIVE',m.id);xbmProtect_(m);xbmSaveManifest_(m);}var done=0,started=Date.now();try{while(m.rollbackCursor>=0&&done<xbmLimit_()&&Date.now()-started<180000){var g=plan.groups[m.rollbackCursor],journal=xbmExistingJournal_(m,g);if(journal){var live=xbmReadLive_(),requests=xbmGroupRequests_(plan,g,live,true,m);if(requests.length)xbmBatch_(requests);xbmVerifyRollback_(plan,g,xbmReadLive_(),m);xbmAuditOnce_(actor,m,g,'rollback',journal.getId());xbmSync_(g.caseId);journal.setContent(JSON.stringify({state:'ROLLED_BACK',migrationId:m.id,reason:m.rollbackReason,group:g}));}m.rollbackCursor--;xbmSaveManifest_(m);done++;}if(m.rollbackCursor<0){XBSolarMigrationPlan.validate(xbmReadLive_());xbmUnprotect_(m);m.state='ROLLED_BACK';xbmSaveManifest_(m);xbmProperties_().deleteProperty('XBSOLAR_MIGRATION_ACTIVE');}return {ok:true,state:m.state,rollbackCursor:m.rollbackCursor,processed:done,backupId:m.backupId};}catch(e){m.lastError=String(e.message).slice(0,1200);xbmSaveManifest_(m);bumpPortalDatabaseRevision_();throw Error('Rollback dừng để tránh ghi đè dữ liệu khác. '+e.message);}});}

function xbmProperties_(){return PropertiesService.getScriptProperties();}
function xbmPointer_(){var s=xbmProperties_().getProperty('XBSOLAR_MIGRATION_JOURNAL');return s?JSON.parse(s):null;}
function xbmAssertPortalWrites_(){if(xbmProperties_().getProperty('XBSOLAR_MIGRATION_ACTIVE'))throw publicError_('Hệ thống đang bổ sung/khôi phục dữ liệu XBSolar. Tạm ngừng ghi; tải lại hồ sơ sau khi quản lý hoàn tất.');}
function xbmAssertNoActive_(){if(xbmProperties_().getProperty('XBSOLAR_MIGRATION_ACTIVE'))throw Error('Đã có migration đang chạy; dùng continue/status/rollback.');}
function xbmLocked_(fn){var lock=LockService.getScriptLock();if(!lock.tryLock(1000))throw Error('Đang có thao tác ghi; thử lại sau.');try{return fn();}finally{lock.releaseLock();}}
function xbmManager_(){var email=String(Session.getActiveUser().getEmail()||'').toLowerCase();if(!email)throw Error('Phải chạy từ Apps Script Editor bằng tài khoản quản lý.');var ss=spreadsheet_(),v=ss.getSheetByName(SHEETS.users).getDataRange().getValues(),h=v.shift(),users=v.map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});return o;}).filter(function(u){return String(u['Email Google']||'').toLowerCase()===email&&bool_(u['Đang hoạt động']);});if(users.length!==1||!resolveRole_(users[0]['Vai trò'],users[0]['Trung tâm']).isGlobalManager)throw Error('Chỉ quản lý toàn hệ thống được chạy migration.');return {email:email,isGlobalManager:true};}
function xbmSha_(value){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,XBSolarMigrationPlan.stable(value),Utilities.Charset.UTF_8).map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('');}
function xbmPlan_(){if(APP_VERSION!=='1.10.3-case-corrections')throw Error('Backend không đúng phiên bản đã kiểm thử.');var id=xbmProperties_().getProperty('XBSOLAR_MIGRATION_BUNDLE_FILE_ID');if(!id)throw Error('Chưa cấu hình file gói migration.');var plan=JSON.parse(DriveApp.getFileById(id).getBlob().getDataAsString('UTF-8')),hash=plan.planHash;delete plan.planHash;if(xbmSha_(plan)!==hash)throw Error('Gói migration bị thay đổi/hash sai.');plan.planHash=hash;if(plan.format!==1||plan.spreadsheetId!==spreadsheet_().getId()||plan.spreadsheetId!=='1EoYBTSAPPOne1VCUMTLQ7W_1jjDOQnQloDWdZyXM5xI')throw Error('Sai database/format migration.');var allowed=XBSolarMigrationPlan.keys,seen={};plan.groups.forEach(function(g){if(seen[g.caseId])throw Error('Mapping trùng case');seen[g.caseId]=true;var local={};g.operations.forEach(function(o){if(!allowed[o.table]||local[o.table+'/'+o.id]||o.after[allowed[o.table]]!==o.id)throw Error('Thao tác/schema/ID không hợp lệ');local[o.table+'/'+o.id]=true;if(o.table==='Hồ sơ thiết bị'&&o.id!==g.caseId)throw Error('Đổi ID case không được phép');if((o.table==='Công việc trung tâm'||o.table==='Luân chuyển thiết bị')&&o.after['Mã hồ sơ']!==g.caseId)throw Error('Sai case của chặng');Object.keys(o.after).forEach(function(k){if(plan.baseline.headers[o.table].indexOf(k)<0)throw Error('Cột ngoài schema');});});});var expected=xbmExpected_(plan);xbmCheckOwnership_(plan,expected);Object.keys(allowed).forEach(function(t){if(expected.tables[t].length!==plan.expectedCounts[t])throw Error('Số dòng dự kiến sai '+t);});return plan;}
function xbmCheckOwnership_(plan,expected){var works={};expected.tables['Công việc trung tâm'].forEach(function(w){works[w['Mã công việc']]=w['Mã hồ sơ'];});plan.groups.forEach(function(g){g.operations.forEach(function(o){if(['Linh kiện sử dụng','Lỗi thiết bị','Tạm dừng SLA'].indexOf(o.table)>=0&&works[o.after['Mã công việc']]!==g.caseId)throw Error('Dòng con thuộc hồ sơ khác: '+o.table+'/'+o.id);});});xbmCheckChronology_(plan);}
function xbmCheckChronology_(plan){var warnings=[];plan.groups.forEach(function(g){g.operations.forEach(function(o){var fields=o.table==='Hồ sơ thiết bị'?['Ngày nhận từ khách','Ngày sẵn sàng trả khách','Ngày trả khách']:o.table==='Công việc trung tâm'?['Ngày trung tâm nhận hàng','Ngày hoàn tất kỹ thuật','Ngày chuyển hàng đi']:null;if(!fields)return;for(var i=0;i<fields.length;i++)for(var j=i+1;j<fields.length;j++){var a=XBSolarMigrationPlan.day(o.after[fields[i]]),b=XBSolarMigrationPlan.day(o.after[fields[j]]);if(a&&b&&b<a){if(!o.before||XBSolarMigrationPlan.day(o.before[fields[i]])!==a||XBSolarMigrationPlan.day(o.before[fields[j]])!==b)throw Error('Migration tạo ngày sai thứ tự: '+o.table+'/'+o.id);warnings.push({caseId:g.caseId,serial:g.serial,recordId:o.id,earlier:fields[i]+': '+a,later:fields[j]+': '+b,note:'Bất thường có sẵn trong production, giữ nguyên hai ngày nguồn; không do migration tạo.'});}}});});return warnings;}
function xbmCommitConsent_(plan){if(xbmProperties_().getProperty('XBSOLAR_COMMIT_PLAN_HASH')!==plan.planHash)throw Error('Chưa xác nhận đúng SHA-256 của gói đã review. Preview không tự cấp quyền commit.');}
function xbmManifest_(){var p=xbmPointer_();if(!p)throw Error('Chưa có journal; chạy prepare trước.');return JSON.parse(DriveApp.getFileById(p.manifestFileId).getBlob().getDataAsString('UTF-8'));}
function xbmSaveManifest_(m){DriveApp.getFileById(xbmPointer_().manifestFileId).setContent(JSON.stringify(m));}
function xbmSameRun_(plan,m){if(plan.id!==m.id||plan.planHash!==m.planHash||xbmPointer_().planHash!==plan.planHash)throw Error('Journal không thuộc đúng gói; không dùng gói mới để resume/rollback.');if(xbmManager_().email!==m.actor)throw Error('Phải dùng tài khoản quản lý đã prepare gói này để resume/rollback.');}
function xbmLimit_(){var n=Number(xbmProperties_().getProperty('XBSOLAR_CASES_PER_RUN')||5);if(!Number.isInteger(n)||n<1||n>10)throw Error('Mỗi lượt chỉ xử lý 1–10 case.');return n;}
function xbmGet_(path){var r=UrlFetchApp.fetch('https://sheets.googleapis.com/v4/spreadsheets/'+spreadsheet_().getId()+path,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(r.getResponseCode()!==200)throw Error('Không đọc được Sheets API: HTTP '+r.getResponseCode());return JSON.parse(r.getContentText());}
function xbmBatch_(requests){if(!requests.length)return;var r=UrlFetchApp.fetch('https://sheets.googleapis.com/v4/spreadsheets/'+spreadsheet_().getId()+':batchUpdate',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},payload:JSON.stringify({requests:requests}),muteHttpExceptions:true});if(r.getResponseCode()!==200)throw Error('Sheets batch thất bại/không xác định: HTTP '+r.getResponseCode()+'. Không gửi lại mù; resume theo journal.');return JSON.parse(r.getContentText());}
function xbmReadLive_(){var names=Object.keys(XBSolarMigrationPlan.keys),meta=xbmGet_('?fields=sheets(properties(sheetId,title,gridProperties),protectedRanges(protectedRangeId,description))'),sheets={};meta.sheets.forEach(function(s){sheets[s.properties.title]=s;});var query=names.map(function(t){if(!sheets[t])throw Error('Thiếu tab '+t);return 'ranges='+encodeURIComponent("'"+t.replace(/'/g,"''")+"'!A1:"+xbmColumn_(sheets[t].properties.gridProperties.columnCount));}).join('&'),data=xbmGet_('/values:batchGet?valueRenderOption=FORMATTED_VALUE&'+query),out={spreadsheetId:spreadsheet_().getId(),headers:{},tables:{},positions:{},lastRows:{},metadata:sheets,formulas:{}};var formulaData=xbmGet_('/values:batchGet?valueRenderOption=FORMULA&'+query);names.forEach(function(t,i){var v=data.valueRanges[i].values||[],h=v[0]||[];out.headers[t]=h;out.tables[t]=[];out.positions[t]={};out.lastRows[t]=Math.max(1,v.length);v.slice(1).forEach(function(r,index){if(!r[0])return;var o={};h.forEach(function(k,j){o[k]=r[j]==null?'':r[j];});var key=String(r[0]);if(out.positions[t][key]!=null)throw Error('Trùng ID live '+t+'/'+key);out.positions[t][key]=index+1;out.tables[t].push(o);if(!out.formulas[t])out.formulas[t]={};out.formulas[t][key]={};var raw=(formulaData.valueRanges[i].values||[])[index+1]||[];h.forEach(function(k,col){if(typeof raw[col]==='string'&&raw[col].charAt(0)==='=')out.formulas[t][key][k]=true;});});});return out;}
function xbmColumn_(n){var s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function xbmComparable_(snapshot){var out={};Object.keys(XBSolarMigrationPlan.keys).forEach(function(t){out[t]={headers:snapshot.headers[t],rows:snapshot.tables[t].map(function(r){return XBSolarMigrationPlan.normalizeRow(r,snapshot.headers[t]);}).sort(function(a,b){return a[XBSolarMigrationPlan.keys[t]].localeCompare(b[XBSolarMigrationPlan.keys[t]]);})};});return XBSolarMigrationPlan.stable(out);}
function xbmMatchBaseline_(plan,live){if(xbmComparable_(live)!==xbmComparable_(plan.baseline))throw Error('Production/schema đã đổi từ snapshot; đọc lại và lập gói mới trước khi ghi.');XBSolarMigrationPlan.validate(live);plan.groups.forEach(function(g){xbmGroupRequests_(plan,g,live,false,{});});}
function xbmExpected_(plan){var s=XBSolarMigrationPlan.validate(plan.baseline),out={headers:plan.baseline.headers,tables:{}};plan.groups.forEach(function(g){g.operations.forEach(function(o){var now=s[o.table][o.id]||null;if(XBSolarMigrationPlan.stable(now)!==XBSolarMigrationPlan.stable(o.before))throw Error('Before snapshot không khớp gói');s[o.table][o.id]=o.after;});});Object.keys(s).forEach(function(t){out.tables[t]=Object.keys(s[t]).map(function(id){return s[t][id];});});XBSolarMigrationPlan.validate(out);return out;}
function xbmMatchExpected_(plan,live){if(xbmComparable_(live)!==xbmComparable_(xbmExpected_(plan)))throw Error('Postflight khác gói dự kiến; giữ khóa để kiểm tra.');}
function xbmExistingJournal_(m,g){var files=DriveApp.getFolderById(m.folderId).getFilesByName('case-'+g.sourceCase+'.json');if(!files.hasNext())return null;var file=files.next();if(files.hasNext())throw Error('Journal case trùng');var data=JSON.parse(file.getBlob().getDataAsString('UTF-8'));if(data.migrationId!==m.id||XBSolarMigrationPlan.stable(data.group)!==XBSolarMigrationPlan.stable(g))throw Error('Journal case bị thay đổi');return file;}
function xbmCaseJournal_(m,g){return xbmExistingJournal_(m,g)||DriveApp.getFolderById(m.folderId).createFile('case-'+g.sourceCase+'.json',JSON.stringify({state:'PREPARED',migrationId:m.id,group:g}),'application/json');}
function xbmCancelled_(g,m){var op=g.operations.find(function(o){return o.table==='Hồ sơ thiết bị';}),r=JSON.parse(JSON.stringify(op.after));r['Trạng thái hồ sơ']='Đã hủy';r['Người hủy']=m.rollbackActor;r['Ngày hủy']=m.rollbackDate;r['Lý do hủy']='Rollback '+m.id+': '+m.rollbackReason;return r;}
function xbmGroupRequests_(plan,g,live,rollback,m){var state=XBSolarMigrationPlan.validate(live),requests=[],nextRows=Object.assign({},live.lastRows),maxRows={};Object.keys(state).forEach(function(t){maxRows[t]=live.metadata[t].properties.gridProperties.rowCount;});var operations=rollback?g.operations.slice().reverse():g.operations;
  if(rollback&&xbmUntouched_(g,state))return [];
  operations.forEach(function(o){var now=state[o.table][o.id]||null,desired=rollback?(g.createdCase?(o.table==='Hồ sơ thiết bị'?xbmCancelled_(g,m):o.after):o.before):o.after,allowed=rollback?o.after:o.before;
    if(XBSolarMigrationPlan.stable(now)===XBSolarMigrationPlan.stable(desired))return;if(XBSolarMigrationPlan.stable(now)!==XBSolarMigrationPlan.stable(allowed))throw Error('Xung đột, không ghi đè '+o.table+'/'+o.id);
    var pos=live.positions[o.table][o.id],h=live.headers[o.table],sheetId=live.metadata[o.table].properties.sheetId;if(XBSolarMigrationPlan.stable(h)!==XBSolarMigrationPlan.stable(plan.baseline.headers[o.table]))throw Error('Schema đổi '+o.table);
    if(pos==null){if(!desired)return;pos=nextRows[o.table]++;if(pos>=maxRows[o.table]){requests.push({appendDimension:{sheetId:sheetId,dimension:'ROWS',length:pos+1-maxRows[o.table]}});maxRows[o.table]=pos+1;}}
    var cells=h.map(function(k){var v=desired?desired[k]:'';if(/^Ngày /.test(k)&&v){var date=XBSolarMigrationPlan.day(v);return {userEnteredValue:{numberValue:Date.parse(date+'T00:00:00Z')/86400000+25569},userEnteredFormat:{numberFormat:{type:'DATE',pattern:'yyyy-mm-dd'}}};}if(k==='Số lượng'&&v!=='')return {userEnteredValue:{numberValue:Number(v)}};return {userEnteredValue:{stringValue:v==null?'':String(v)}};});
    if(now){h.forEach(function(k,col){if(XBSolarMigrationPlan.stable(now[k])===XBSolarMigrationPlan.stable(desired?desired[k]:''))return;if(live.formulas&&live.formulas[o.table]&&live.formulas[o.table][o.id]&&live.formulas[o.table][o.id][k])throw Error('Không ghi đè công thức: '+o.table+'/'+o.id+'/'+k);requests.push({updateCells:{range:{sheetId:sheetId,startRowIndex:pos,endRowIndex:pos+1,startColumnIndex:col,endColumnIndex:col+1},rows:[{values:[cells[col]]}],fields:/^Ngày /.test(k)&&desired&&desired[k]?'userEnteredValue,userEnteredFormat.numberFormat':'userEnteredValue'}});});}
    else requests.push({updateCells:{range:{sheetId:sheetId,startRowIndex:pos,endRowIndex:pos+1,startColumnIndex:0,endColumnIndex:h.length},rows:[{values:cells}],fields:'userEnteredValue,userEnteredFormat.numberFormat'}});
  });return requests;
}
function xbmVerifyGroup_(plan,g,live){var state=XBSolarMigrationPlan.validate(live);g.operations.forEach(function(o){if(XBSolarMigrationPlan.stable(state[o.table][o.id]||null)!==XBSolarMigrationPlan.stable(o.after))throw Error('Readback sai '+o.table+'/'+o.id);});}
function xbmUntouched_(g,state){return g.operations.every(function(o){return XBSolarMigrationPlan.stable(state[o.table][o.id]||null)===XBSolarMigrationPlan.stable(o.before);});}
function xbmVerifyRollback_(plan,g,live,m){var state=XBSolarMigrationPlan.validate(live);if(xbmUntouched_(g,state))return;g.operations.forEach(function(o){var expected=g.createdCase?(o.table==='Hồ sơ thiết bị'?xbmCancelled_(g,m):o.after):o.before;if(XBSolarMigrationPlan.stable(state[o.table][o.id]||null)!==XBSolarMigrationPlan.stable(expected))throw Error('Rollback readback sai '+o.id);});}
function xbmAuditOnce_(actor,m,g,action,journalId){var marker=m.id+'/'+g.sourceCase+'/'+action,v=xbmGet_('/values/'+encodeURIComponent("'Nhật ký thay đổi'!A1:H")+'?valueRenderOption=FORMATTED_VALUE').values||[];if(v.some(function(r){return String(r[7]||'').indexOf('"marker":"'+marker+'"')>=0;}))return;audit_(actor,'XBSolar migration '+action,'Hồ sơ',g.caseId,'XBSolar Center',null,{marker:marker,sourceCase:g.sourceCase,journalFileId:journalId,operations:g.operations.length,reason:action==='rollback'?m.rollbackReason:'Bổ sung lịch sử XBSolar đã đối chiếu'});}
function xbmSync_(caseId){var live=xbmReadLive_(),oldRead=readTable_,oldRows=readTableWithRows_;bumpPortalDatabaseRevision_();readTable_=function(name){return live.tables[name]||oldRead(name);};readTableWithRows_=function(name){if(!live.tables[name])return oldRows(name);return {headers:live.headers[name],rows:live.tables[name].map(function(r){return Object.assign({},r,{__rowNumber:live.positions[name][r[XBSolarMigrationPlan.keys[name]]]+1});})};};try{var a=syncDashboardProjectionCase_(caseId),b=syncPortalCaseIndexCase_(caseId);if(!a||!a.ok||!b||!b.ok)throw Error('Đồng bộ projection/index chưa hoàn tất '+caseId);SpreadsheetApp.flush();}finally{readTable_=oldRead;readTableWithRows_=oldRows;bumpPortalDatabaseRevision_();}}
function xbmProtect_(m){var meta=xbmGet_('?fields=sheets(properties(sheetId,title),protectedRanges(protectedRangeId,description))'),description='XBSolar migration '+m.id,requests=[],ids=[];Object.keys(XBSolarMigrationPlan.keys).forEach(function(t){var s=meta.sheets.find(function(s){return s.properties.title===t;});if(!s)throw Error('Thiếu tab bảo vệ');var own=(s.protectedRanges||[]).filter(function(p){return p.description===description;});own.forEach(function(p){ids.push(p.protectedRangeId);});if(!own.length)requests.push({addProtectedRange:{protectedRange:{range:{sheetId:s.properties.sheetId},description:description,warningOnly:false,editors:{users:[m.actor]}}}});});if(requests.length){var result=xbmBatch_(requests);(result.replies||[]).forEach(function(r){if(r.addProtectedRange)ids.push(r.addProtectedRange.protectedRange.protectedRangeId);});}m.protectedRanges=ids;}
function xbmUnprotect_(m){var meta=xbmGet_('?fields=sheets(properties(title),protectedRanges(protectedRangeId,description))'),requests=[],owned=m.protectedRanges||[];meta.sheets.filter(function(s){return !!XBSolarMigrationPlan.keys[s.properties.title];}).forEach(function(s){(s.protectedRanges||[]).filter(function(p){return owned.indexOf(p.protectedRangeId)>=0;}).forEach(function(p){if(p.description!=='XBSolar migration '+m.id)throw Error('Bảo vệ của migration đã bị đổi; không xóa cấu hình khác.');requests.push({deleteProtectedRange:{protectedRangeId:p.protectedRangeId}});});});if(requests.length)xbmBatch_(requests);}
